# Import Conventions
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
import seaborn as sns  
import statsmodels as sm  

# NumPy
NumPy short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.  
Many computational packages providing scientific functionality use NumPy’s array objects as one of the standard interface lingua francas for data exchange.

In [1]:
import numpy as np

## N-dimensional array
All of the elements must be the same type.

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [8]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

### Creating ndarray from a list.

In [14]:
data_list = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr = np.array(data_list)

In [19]:
arr.ndim

2

In [18]:
arr.shape

(2, 4)

In [20]:
arr.dtype

dtype('int64')

### Functions to create new arrays

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[5.47383008e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [6.88460314e-310, 3.92738306e-033]],

       [[1.04876599e-042, 7.25341356e+169],
        [1.13827268e-042, 3.54162782e-061],
        [1.53324168e-075, 3.83623950e+175]]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [32]:
arr1.dtype

dtype('float64')

### Explicitly convert or cast an array from one data type to another using ndarray’s astype method

In [36]:
arr_int = np.array([1, 2, 3], dtype=np.int32)

In [40]:
arr_int.dtype

dtype('int32')

In [41]:
arr_float = arr_int.astype(np.float64)

In [42]:
arr_float.dtype

dtype('float64')